### ISSUE TITLE
README 中怼杠精是啥情况？

### ISSUE THREAD

**Issue by Rayn-liuwei** [TheKingOfDuck/easyXssPayload#1]
README 中怼杠精是啥情况？

**Comment by TheKingOfDuck** [comment]
@Rayn-liuwei 先知社区有个“爱我的灵魂”说`早八百年的就不玩的东西了,拿出来秀？？？`
当时非常不爽，见没人这样分享过这种搞法，就分享了一下，结果他就来抬杠了。
